# Force OS X.
language: objective-c
os: osx
rvm: system

matrix:
  include:
    - env: OSX=10.14
      osx_image: xcode10.1
    - env: OSX=10.13
      osx_image: xcode9.4

before_install:
    - brew update

install:
    # Make sure python is installed
    - brew list python@2 || brew install python@2
    - brew outdated python@2 || brew upgrade python@2
    - brew install Formula/python27@16.rb
    # Make sure python3 is installed
    - brew list python || brew install python
    - brew outdated python || brew upgrade python
    - brew install Formula/python37@3.rb
    - brew install Formula/python37@4.rb

script:
    - brew test Formula/python27@16.rb
    - brew test Formula/python37@3.rb
    - brew test Formula/python37@4.rb
